language: php

cache:
    directories:
        - $HOME/.composer/cache

jobs:
    fast_finish: true
    include:
        - php: 7.3
          env: SYMFONY_VERSION=4.4.* COMPOSER_FLAGS="--prefer-lowest"
        - php: 7.4
          env: SYMFONY_VERSION=5.1.* SYMFONY_DEPRECATIONS_HELPER="max[self]=0"
        - php: 8.0
          env: SYMFONY_VERSION=5.2.* COMPOSER_FLAGS="--prefer-stable"

env:
    global:
        - SYMFONY_DEPRECATIONS_HELPER="max[total]=999"
        - COMPOSER_FLAGS="--prefer-dist"
        - DEPENDENCIES=dist

before_install:
    - composer self-update
    - |
      if [ "$SYMFONY_VERSION" != "" ]; then
           sed -ri 's/"symfony\/(.+)": "(.+)"/"symfony\/\1": "'$SYMFONY_VERSION'"/' composer.json;
      fi;
    - if [ "$DEPENDENCIES" = "dev" ]; then perl -pi -e 's/^}$/,"minimum-stability":"dev"}/' composer.json; fi;

install: composer update $COMPOSER_FLAGS --no-interaction
